### ISSUE TITLE
Use template files instead of strings

### ISSUE THREAD

**Issue by anarchyrucks** [google/zoekt#102]
zoekt uses in-memory template strings instead of separate files which makes it difficult to add features to the web interface. Moving these strings to the files should be the way forward to make development of the web interface easier.

**Comment by anarchyrucks** [comment]
I see that there is an option to dump the template but I'm not really sure why it was the design decision. Can somebody clear it up for me?

I wanted to add some GUI filters and I removed the template strings and added template files but I don't know if the project wants go in that direction.

[filters](https://i.imgur.com/kfWUsI9.png)

**Comment by hanwen** [comment]
there already is an option, see here https://github.com/google/zoekt/blob/b1730d8e0cc4aa35d6b2d593b83fef7cb0c81673/cmd/zoekt-webserver/main.go#L118
