### ISSUE TITLE
zoekt cannot list enough search results

### ISSUE THREAD

**Issue by dna2github** [google/zoekt#123]
we find that zoekt cannot list enough search results to match the page number for example `num=50`.

how to reproduce:
- git clone `github.com/nodejs/node` and index the project
- run zoekt-webserver and search for `project:node set_.*_cache`
<img width="668" alt="Screen Shot 2020-10-25 at 12 38 30 AM" src="https://user-images.githubusercontent.com/2894341/97087178-a1a8e400-165a-11eb-89d1-306bc82d61e2.png">
- search for `project:node set_m.*_cache`
<img width="409" alt="Screen Shot 2020-10-25 at 12 38 42 AM" src="https://user-images.githubusercontent.com/2894341/97087200-c604c080-165a-11eb-9623-7b752d2cf852.png">

the latter results are not in the former one. this issue also exists not only for regular expression but also for a simple word search. and it can be resolved by increasing the `num`; however, it does not match the page number (page_size = 50, file_match < 50, doc_match < 50).

```
{
      "query": "r:z.node set_.*_cache",
      "page_size": 50,
      "file_match": 10,
      "ngram_match": 5844,
      "doc_match": 21,
      "doc_n": 10
}
```

```
{
      "query": "r:z.node set_.*_cache",
      "page_size": 100,
      "file_match": 51,
      "ngram_match": 19362,
      "doc_match": 108,
      "doc_n": 51
}
```

**Comment by hanwen** [comment]
this UI looks unfamiliar, and https://cs.bazel.build/search?q=r%3Azoekt+page_size shows that zoekt doesnt contain the symbol "page_size", and the query language doesn't support the "project:" atom. Which software are you reporting bugs for?

**Comment by hanwen** [comment]
typically, the search is abandoned after enough "interesting" matches (ie. symbol definitions) are returned. If this happens, the Zoekt UI will print a "show more" link.

**Comment by dna2github** [comment]
actually it is from customized template:

```
   "stat" : {
      {{if .Stats.Crashes}}"crashes": "{{JsonText .Stats.Crashes}}",{{end}}
      "query": "{{JsonText .Last.Query}}",
      "page_size": {{.Last.Num}},
      "file_match": {{len .FileMatches}},
      "ngram_match": {{.Stats.NgramMatches}},
      "doc_match": {{.Stats.MatchCount}},
      "doc_n": {{.Stats.FileCount}},
      {{if .Stats.Wait}}"wait": {{.Stats.Wait}},{{end}}
      {{if .Stats.FilesSkipped}}"file_skipped": {{.Stats.FilesSkipped}},{{end}}
      {{if .Stats.ShardsSkipped}}"shard_skipped": {{.Stats.ShardsSkipped}},{{end}}
      "file_considered": {{.Stats.FilesConsidered}},
      "file_loaded": {{.Stats.FilesLoaded}},
      "duration": "{{.Stats.Duration}}"
   },
```
