### ISSUE TITLE
zoekt-git-index fails with indexGitRepo(...): reference not found

### ISSUE THREAD

**Issue by henrik242** [google/zoekt#133]
`zoekt-git-index` has started failing for us.  The only change I can see in the indexing output is

    indexGitRepo(/home/travis/gopath/src/github.example.io/foo/codesearch/github_repos/github.example.io/foo/foo-incident-starter.git): reference not found

It seems to finish all indexing, but fails with exit 1 at the end.

**Comment by hanwen** [comment]
> started failing for us

after an upgrade of anything, or just out of the blue?

**Comment by henrik242** [comment]
@hanwen Any ideas if this could be fixed?

**Comment by hanwen** [comment]
I added a test for indexing an empty repo in https://gerrit-review.googlesource.com/c/zoekt/+/313865

the test passes. I suspect something else is wrong. Can you delve a little bit deeper?

**Comment by henrik242** [comment]
Thanks! Changes in zoekt might have improved things since I opened this issue. I haven't actually seen this lately, but I'll investigate some more.

**Comment by hanwen** [comment]
I'll close this for now. Please reopen when you find something.

**Comment by henrik242** [comment]
@hanwen This failed for us again. I haven't got any more debug data than the `reference not found` message above. We run zoekt againt Github Enterprise (v3.1.4), I don't know it that has anything to do with it.
