### ISSUE TITLE
Bazel sandbox was refactored

### ISSUE THREAD

**Issue by TobiX** [google/zoekt#18]
In https://github.com/google/zoekt#symbol-search there is a mini-howto to build the bazel sandbox, but the code seems to have changed in bazel. I got a working binary using these steps:

1. Get `process-tools.h process-tools.cc linux-sandbox.cc linux-sandbox.h linux-sandbox-options.cc linux-sandbox-options.h linux-sandbox-pid1.cc linux-sandbox-pid1.h linux-sandbox-utils.h` from the same path.
2. Replace some includes: `sed -i 's|src/main/tools/||' *.{cc,h}`
3. Compile with g++: `g++ -Wall -std=c++11 -o linux-sandbox linux-sandbox.cc linux-sandbox-options.cc linux-sandbox-pid1.cc process-tools.cc`

The resulting `linux-sandbox` tool seems to work in a similar way to the old `namespace-sandbox` tool...

**Comment by hanwen** [comment]
The doc is out of date. I added a custom sandbox under cmd/zoekt-sandbox.

**Comment by hanwen** [comment]
the real solution btw is to fix https://github.com/universal-ctags/ctags/issues/1372 and use seccomp. seccomp was intended as a security mechanism, so it'll be much more effective than namespaces.

**Comment by hanwen** [comment]
See https://gerrit-review.googlesource.com/106993,

If you can review and give  +1 , that'd be great (patrick normally does this but is on a holiday.)
