### ISSUE TITLE
anchor to results is wrong

### ISSUE THREAD

**Issue by vpereira** [google/zoekt#20]
Hi,

if i search for a term, and I'm running the webserver with "-print", then I get the results, and you have the line number as link to the place where the search term was found. However the anchor is wrong (i.e if you click in the line number, it doesn't bring you to the exact line number)

so I was able to fix it with:

```
diff --git a/web/templates.go b/web/templates.go
index 7e95a28..419f8f2 100644
--- a/web/templates.go
+++ b/web/templates.go
@@ -151,7 +151,7 @@ To list repositories, try:
       {{else}}
         <div style="background: #eef;">
         {{range .Matches}}
-          <pre>{{if .URL}}<a href="{{.URL}}">{{end}}{{.LineNum}}{{if .URL}}</a>{{end}}: {{range .Fragments}}{{.Pre}}<b>{{.Match}}</b>{{.Post}}{{end}}</pre>
+          <pre>{{if .URL}}<a href="{{.URL}}l{{.LineNum}}">{{end}}{{.LineNum}}{{if .URL}}</a>{{end}}: {{range .Fragments}}{{.Pre}}<b>{{.Match}}</b>{{.Post}}{{end}}</pre>
         {{end}}
         </div>
       {{end}}

```

However could you tell me how would be the best way to fix it? Maybe in the method where we generate the URL with fragments? Or maybe some defensive logic in the template to avoid issues when the LineNum doesn't exist?

**Comment by hanwen** [comment]
I suspect this will break links for github/gitiles etc., so the change should be somewhere else. I can have a look this week.

**Comment by hanwen** [comment]
see  https://gerrit-review.googlesource.com/108199 and https://gerrit-review.googlesource.com/108200

**Comment by vpereira** [comment]
oh great, indeed a better place to fix it.

**Comment by vpereira** [comment]
will we get it merged into master?

**Comment by hanwen** [comment]
I already submitted it. The real source of truth is actually https://gerrit.googlesource.com/zoekt (I mirror to github every once in a while.)

**Comment by dgryski** [comment]
@hanwen can it be set to automatically mirror?

**Comment by vpereira** [comment]
> @hanwen can it be set to automatically mirror?
yup, maybe i'm missing something, but I wasn't able to go get on gerrit..

**Comment by hanwen** [comment]
I actually work in the infrastructure that powers googlesource.com, and we should set up something automatic, but there's so many other important things to do, so it keeps slipping. The same for "go get" support.

**Comment by hanwen** [comment]
commit 128ced7a3cab72087733cf44a2d56ce6c66f8081
Author: Han-Wen Nienhuys <hanwen@google.com>
Date:   Tue May 30 18:20:09 2017 +0200

    web: don't auto focus the search box on the file print page
    
    This fixes #fragment links in -print mode.
    
    Change-Id: I0a8f255167f43ffa7597a3e3f8f3b910d4b363b3

commit 643f171a1eb1107c9d920417679a96bcf8dd8bc9
Author: Han-Wen Nienhuys <hanwen@google.com>
Date:   Tue May 30 18:19:13 2017 +0200

    web: populate the fragment in -print mode
    
    Change-Id: I68d8f13e0cfbdc09f0ff8361b0111167ca601f87
