### ISSUE TITLE
ctags timeout configurable?

### ISSUE THREAD

**Issue by vpereira** [google/zoekt#24]
Hi,

can we set the ctags timeout configurable? I think the default for large codebases and not so powerful machines, sometimes isn't enough. I have a patch to do it that i could send it via pull request (zoekt-index gets a new argument which is passed to build/ctags.go. if nothing is given, default is assumed)

**Comment by hanwen** [comment]
I'm going to revisit the ctags support soon, in light of

  https://github.com/universal-ctags/ctags/commit/5d82ee6e92ee9cdda5cc9dcee91646dd678b4b42

this will likely remove the need for batching files and timeouts.

**Comment by hanwen** [comment]
please try installing universal-ctags (with --_interactive support) as universal-ctags.
