### ISSUE TITLE
Ignore .svn directories?

### ISSUE THREAD

**Issue by kohlerm** [google/zoekt#3]
Hi, 
We still have some repositories in subversion,which creates .svn directories for its meta-data.  
It seems that the .git get skipped by the git indexer. 
It would be useful to also skip the .svn folders, or more generically offer a way to skip directories, e.g everything in .gitignore maybe?

**Comment by hanwen** [comment]
are you talking about the git indexer or the file system indexer ?

**Comment by kohlerm** [comment]
File system indexer. E.g when I checkout a project from subversion I get those .svn subdirectories similiar to the .git directories. When I later search in this project I get matches in those .svn subdirectories which isn't helpful

**Comment by hanwen** [comment]
https://gerrit-review.googlesource.com/#/c/79741/
