### ISSUE TITLE
Append to old index

### ISSUE THREAD

**Issue by Som3** [google/zoekt#67]
I have a folder with many projects and indexed it, later create new project into a folder and how can I add it project to the index without reindexing all folder?

**Comment by Som3** [comment]
```
mkdir folderA
cd folderA
mkdir folderB
zoekt-index -index_dir=/home/user/my-index .
```
after
```
cd folderA
mkdir folderC
```

Can I add `folderC` to exists index `/home/user/my-index` ?

**Comment by hanwen** [comment]
No. You should index the directories separately.

**Comment by Som3** [comment]
If indexed separately and search without specifing index_dir - can I define from what project it matched result?

**Comment by hanwen** [comment]
use the r: operator.
