### ISSUE TITLE
builtin source browser should support line anchors.

### ISSUE THREAD

**Issue by vpereira** [google/zoekt#7]
Hi,

I'm using zoekt to index src rpms, before build it, after that the patches are already applied, and I'm wondering if zoekt is the right tool. The index and search tool, work as expected, however I see that if I search for a term, in the results page the links to the code number are wrong, pointing to the searched term. I.e if my search looks like http://127.0.0.1:6070/search?q=TIFFLinkDirectory&num=50, every single line in the results page will link to http://127.0.0.1:6070/search?q=TIFFLinkDirectory&num=50#
I don't know if its a bug or thats related with the way that I'm using it. Does it should link to a code browser kind like http://lxr.linux.no/? If not, do you have any recommendation of code browser, which could interact well with zoekt (without reimplement the same features?)

**Comment by hanwen** [comment]
There is a -print option to the webserver that should let you search the code as it was indexed.

**Comment by vpereira** [comment]
oh great!  any plans to have the code then being rendered with line codes?

**Comment by hanwen** [comment]
no, but happily will take a change that implements that :-)

**Comment by vpereira** [comment]
thank you!
