### ISSUE TITLE
cs.bazel.build doesn't find a string that's definitely there

### ISSUE THREAD

**Issue by philwo** [google/zoekt#8]
When searching for "spawn_strategy":
http://cs.bazel.build/search?q=r%3Abazel+spawn_strategy&num=50

I expected this hit to show up:
https://github.com/bazelbuild/bazel/blob/ce74be1e9e25929cc4d4e891f37ba29b9a74ed8c/src/main/java/com/google/devtools/build/lib/bazel/rules/BazelRulesModule.java#L51

But it doesn't. Not sure why, or how to debug further.

**Comment by hanwen** [comment]
var fileStart uint32
			if s.fileIdx > 0 {
				fileStart = s.ends[s.fileIdx-1]
			}
..
	cand := &candidateMatch{
				runeOffset:  p1 - fileStart - s.leftPad,
			}



fileStart is in bytes, but runeOffset is in runes.

**Comment by hanwen** [comment]
it gets worse:

(constructing postings, runes)
 	newOff := s.end + uint32(runeIndex) - 2

	s.end += dataSz

**Comment by dgryski** [comment]
Maybe create `byteOffset` and `runeOffset` types? :/

**Comment by hanwen** [comment]
some problems fixed in https://gerrit-review.googlesource.com/c/97439/ , but there is still another bug lurking.

I've rolled back cs.bazel to zoekt-2017-01-16T1746-c5533f5 . The reindexing may take an hour or so.

**Comment by hanwen** [comment]
the following is translating from rune offsets to byte offsets. However, the sample vector should be indexed by corpus-rune offset, but candidateMatch provides offsets per document.

it is surprisingly hard to isolate in a test case, or it is just too late and I should go to bed.


// Find offset in bytes for an offset in runes.
func (p *contentProvider) findOffset(filename bool, r uint32) uint32 {
	sample := p.id.runeOffsets
	if filename {
		sample = p.id.fileNameRuneOffsets
	}
	start := sample[r/runeOffsetFrequency]
	left := r % runeOffsetFrequency

	data := p.data(filename)[start:]

**Comment by hanwen** [comment]
several utf-8 bugs fixed now. Closing.
