### ISSUE TITLE
Allow zoekt-git-index to index all branches

### ISSUE THREAD

**Issue by sschuberth** [google/zoekt#9]
There should be an easy syntax for letting `zoekt-git-index` do index all branches without having to list them all by name.

**Comment by hanwen** [comment]
yeah, that could be a command-line option. Would you be willing to contribute a patch?

**Comment by sschuberth** [comment]
I'm not very fluent at Go yet, but I could give it a try. However, instead of a separate command line option, I was actually thinking of allowing the strings passed to `-branches` to be glob patterns. So `-branches stable-*` would index all stable branches, and `-branches *` would index all branches as requested. What do you think?

**Comment by hanwen** [comment]
that's a nice idea. Maybe you could even do something like "stable/*" to handle nested namespaces too.

**Comment by sschuberth** [comment]
Exactly. Doing it that way definitely makes sense to me, but would also be more involving. Not sure if I'm able to contribute this soon.
