### ISSUE TITLE
Feature request: BitBucket mirror - Delete stale repos

### ISSUE THREAD

**Issue by nikos912000** [google/zoekt#91]
When I implemented the BitBucket mirror I didn't implement the [deleteStaleRepos](https://github.com/google/zoekt/blob/master/cmd/zoekt-mirror-github/main.go#L160) method which is available in the GH/GL mirrors.

Opening this ticket to work on this.

**Comment by hanwen** [comment]
fixed in https://gerrit-review.googlesource.com/c/zoekt/+/232412

956bc1b48ae3e00a924edfccdd20b62ce75dfb91
